### PR TITLE
Update to 4.2.0

### PR DESCRIPTION
**Pull request by sourcedelica**
Updated to 4.2.0, including the manually copied `zmq.hpp`.  Should we change the recipe to pull `zmq.hpp` from Github?

Also if possible I'd like to [resolve the link warnings](https://github.com/conan-io/conan/issues/732).

### CODE REVIEW

**Comment by sourcedelica** [comment]
Also we may want to rename the package to `cppzmq` since seems to be the official name.

**Comment by sourcedelica** [comment]
I've posted on the ZMQ mailing list about getting a tag for cppzmq.  It's kindof an orphan right now.

**Comment by memsharded** [comment]
Manually copying the zmq.hpp is not bad, can be done, though it is usually more consistent to reference an external source, like a github repo, but it is true that it should be tagged.

Sure, lets change the name to cppzmq if that is the official one!

Could you please try to address those things? I'll keep working on the libzmq 4.2.0 version, we will need it in order to make this one work. Thank you!

**Comment by sourcedelica** [comment]
Will do - thx!

**Comment by sourcedelica** [comment]
I saw your tweet about libzmq 4.2.0.  That's awesome!  I'll take care of this this weekend.

**Comment by sourcedelica** [comment]
Please take a look when you have a chance.  They said they didn't want to tag the cppzmq repo.  So I added a `sha1` property.   So it should be ready to go.

Re: the libzmq update - looks great.  One thing - MacOS does not require `-pthread`, so if you could put a condition into the libzmq Conanfile removing `-pthread` for Mac that would remove a warning on each build:

    clang: warning: argument unused during compilation: '-pthread'

It is adding Macos to this condition:

            if not self.settings.os == "Windows" and not self.settings.os == "Macos":
                self.cpp_info.cppflags = ["-pthread"]

Thanks!

**Comment by memsharded** [comment]
Thanks very much for your PR, I have merged it, added a couple of details: https://github.com/memsharded/conan-zmqcpp/commit/6800ce6607a9ce9b6d11c3e62db1f3989f99f9f0

I have already published it in conan.io: https://www.conan.io/source/cppzmq/4.2.0/memsharded/stable

**Pull request merged**
